[project]
name = "ftl_collections"
version = "0.1.7"

[tool.setuptools.packages.find]
where = ["src"]
include = ["ansible_collections*"]
namespaces = false

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
